# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(452, 499)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background : #8B0000")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton7.setGeometry(QtCore.QRect(110, 310, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton7.setFont(font)
        self.pushButton7.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"\n"
"    background:linear-gradient(to bottom, #fe1a00 5%, #ce0100 100%);\n"
"    background-color:#fe1a00;\n"
"    border-radius:11px;\n"
"    border:3px solid #d83526;\n"
"    \n"
"    \n"
"    color:#ffffff;\n"
"    \n"
"    padding:14px 60px;\n"
"    text-decoration:none;\n"
"    \n"
"}\n"
"QPushButton{\n"
"    background:linear-gradient(to bottom, #ce0100 5%, #fe1a00 100%);\n"
"    background-color:#ce0100;\n"
"}\n"
"QPushButton {\n"
"    position:relative;\n"
"    top:1px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.pushButton7.setIconSize(QtCore.QSize(20, 20))
        self.pushButton7.setObjectName("pushButton7")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 30, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("color :white")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 100, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("color :white")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(100, 150, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("color :white")
        self.comboBox.setObjectName("comboBox")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 100, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    \n"
"    background:linear-gradient(to bottom, #fe1a00 5%, #ce0100 100%);\n"
"    background-color:#fe1a00;\n"
"    border-radius:11px;\n"
"    border:3px solid #d83526;\n"
"    \n"
"    \n"
"    color:#ffffff;\n"
"    \n"
"    padding:11px 21px;\n"
"    text-decoration:none;\n"
"    \n"
"}\n"
"QPushButton {\n"
"    background:linear-gradient(to bottom, #ce0100 5%, #fe1a00 100%);\n"
"    background-color:#ce0100;\n"
"}\n"
"QPushButton {\n"
"    position:relative;\n"
"    top:1px;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 40, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color : white")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color :white")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 152, 71, 31))
        self.label_3.setStyleSheet("color :white")
        self.label_3.setObjectName("label_3")
        self.pushButton3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton3.setGeometry(QtCore.QRect(320, 30, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton3.setFont(font)
        self.pushButton3.setStyleSheet("QPushButton {\n"
"\n"
"    background:linear-gradient(to bottom, #fe1a00 5%, #ce0100 100%);\n"
"    background-color:#fe1a00;\n"
"    border-radius:11px;\n"
"    border:3px solid #d83526;\n"
"    \n"
"    \n"
"    color:#ffffff;\n"
"    \n"
"    padding:11px 21px;\n"
"    text-decoration:none;\n"
"}\n"
"QPushButton {\n"
"    background:linear-gradient(to bottom, #ce0100 5%, #fe1a00 100%);\n"
"    background-color:#ce0100;\n"
"}\n"
"QPushButton {\n"
"    position:relative;\n"
"    top:1px;\n"
"}\n"
"")
        self.pushButton3.setObjectName("pushButton3")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(40, 250, 391, 23))
        self.progressBar.setStyleSheet("color : white")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 410, 181, 31))
        self.label_6.setStyleSheet("color : white")
        self.label_6.setObjectName("label_6")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(330, 410, 121, 21))
        self.label_45.setStyleSheet("color : white")
        self.label_45.setObjectName("label_45")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(340, 370, 91, 20))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 452, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton7.setText(_translate("MainWindow", "Dowanload "))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter The URL  "))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Save Location "))
        self.pushButton_2.setText(_translate("MainWindow", "Browser"))
        self.label.setText(_translate("MainWindow", "     URL"))
        self.label_2.setText(_translate("MainWindow", "Save Location "))
        self.label_3.setText(_translate("MainWindow", "   Qualty"))
        self.pushButton3.setText(_translate("MainWindow", "searsh"))
        self.label_6.setText(_translate("MainWindow", "Crated By Ahmed Mchiri ; Kamel mchiri"))
        self.label_45.setText(_translate("MainWindow", "Version 1.0 ©"))
